spring.application.name=auth-boilerplate

spring.datasource.url=jdbc:postgresql://localhost:5432/khata-backend-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=ZV9KQ3h5dFJmTnB4QmV3Y1N6WkR2aFh5VnBqR3dTQmN4Y1p6V0tYQ3h6RkN2cFh7TnB5WkRzQmV4Y1N6dFh2VnBqR3dTQmN4Y1p6
jwt.expiration=18000000

logging.level.org.springframework.security=INFO
